import type { Scenario } from "./schema";

export const familyIoTScenario: Scenario = {
  id: "family_iot_sprawl_v1",
  title: "Family Home with IoT Sprawl",
  description: "A typical suburban home with multiple family members and various smart devices. Notice how IoT devices are isolated on their own network for security.",
  environment: {
    type: "home",
    isp: "FictionalNet",
    publicIp: "203.0.113.12",
  },
  networks: [
    { id: "main", ssid: "MapleHouse_Main", security: "WPA2", subnet: "192.168.10.0/24", zone: "main" },
    { id: "guest", ssid: "MapleHouse_Guest", security: "WPA2", subnet: "192.168.20.0/24", zone: "guest" },
    { id: "iot", ssid: "MapleHouse_IoT", security: "WPA2", subnet: "192.168.30.0/24", zone: "iot" },
  ],
  devices: [
    {
      id: "router",
      type: "router",
      label: "Home Router",
      networkId: "main",
      ip: "192.168.10.1",
      localId: "A0:B1:C2:D3:E4:F5",
      riskFlags: [],
      description: "The central hub of your home network. All traffic flows through this device.",
      manufacturer: "NetGear",
      openPorts: [80, 443],
    },
    {
      id: "laptop_work",
      type: "laptop",
      label: "Work Laptop",
      networkId: "main",
      ip: "192.168.10.14",
      localId: "AA:BB:CC:11:22:33",
      riskFlags: [],
      description: "A work-issued laptop used for remote work. Connected to the main network for full access.",
      manufacturer: "Dell",
      protocols: ["HTTPS", "SSH", "RDP"],
    },
    {
      id: "phone_mom",
      type: "phone",
      label: "Mom's iPhone",
      networkId: "main",
      ip: "192.168.10.22",
      localId: "DD:EE:FF:44:55:66",
      riskFlags: [],
      description: "Personal smartphone with banking and social media apps.",
      manufacturer: "Apple",
      protocols: ["HTTPS", "iMessage"],
    },
    {
      id: "tablet_kid",
      type: "tablet",
      label: "Kids' iPad",
      networkId: "main",
      ip: "192.168.10.31",
      localId: "11:22:33:AA:BB:CC",
      riskFlags: [],
      description: "Tablet used by children for education and entertainment.",
      manufacturer: "Apple",
      protocols: ["HTTPS", "YouTube"],
    },
    {
      id: "smarttv",
      type: "smarttv",
      label: "Living Room TV",
      networkId: "iot",
      ip: "192.168.30.10",
      localId: "77:88:99:AA:BB:CC",
      riskFlags: ["iot_device"],
      description: "Smart TV with streaming apps. Isolated on IoT network to limit potential vulnerabilities.",
      manufacturer: "Samsung",
      protocols: ["HTTPS", "Netflix", "Disney+"],
    },
    {
      id: "camera_indoor",
      type: "camera",
      label: "Indoor Camera",
      networkId: "iot",
      ip: "192.168.30.21",
      localId: "EE:FF:00:11:22:33",
      riskFlags: ["iot_device", "default_password"],
      description: "Security camera monitoring the living room. Warning: Still using default password!",
      manufacturer: "Wyze",
      openPorts: [80, 554],
    },
    {
      id: "thermostat",
      type: "thermostat",
      label: "Smart Thermostat",
      networkId: "iot",
      ip: "192.168.30.15",
      localId: "44:55:66:77:88:99",
      riskFlags: ["iot_device"],
      description: "Controls home temperature and can be accessed remotely.",
      manufacturer: "Nest",
      protocols: ["HTTPS"],
    },
    {
      id: "speaker",
      type: "speaker",
      label: "Voice Assistant",
      networkId: "iot",
      ip: "192.168.30.25",
      localId: "BB:CC:DD:EE:FF:00",
      riskFlags: ["iot_device"],
      description: "Smart speaker with voice assistant. Always listening for wake word.",
      manufacturer: "Amazon",
      protocols: ["HTTPS", "Alexa"],
    },
    {
      id: "guest_phone",
      type: "phone",
      label: "Guest's Phone",
      networkId: "guest",
      ip: "192.168.20.5",
      localId: "12:34:56:78:9A:BC",
      riskFlags: [],
      description: "A visitor's phone connected to the guest network. Cannot access main network devices.",
      manufacturer: "Samsung",
    },
    {
      id: "mystery_device",
      type: "unknown",
      label: "Generic Smart Controller",
      networkId: "iot",
      ip: "192.168.30.99",
      localId: "FF:00:11:22:33:44",
      riskFlags: ["unknown_device", "forgotten_device"],
      description: "An unidentified device on your network. When did this connect? What is it?",
    },
    {
      id: "old_tablet",
      type: "tablet",
      label: "Old Tablet (Inactive)",
      networkId: "main",
      ip: "192.168.10.50",
      localId: "99:AA:BB:CC:DD:EE",
      riskFlags: ["forgotten_device", "outdated_firmware"],
      description: "An old tablet that hasn't been updated in 2 years. Still connected but rarely used.",
      manufacturer: "Samsung",
    },
  ],
  events: [
    {
      id: "unknown_device_reveal",
      trigger: "onEnter",
      deviceId: "mystery_device",
      message: "An unfamiliar device appears on your IoT network. You don't remember adding this...",
    },
  ],
  learningPrompts: [
    {
      id: "prompt_private_ip",
      question: "Which of these is a private IP address?",
      answers: [
        { text: "192.168.10.14", isCorrect: true },
        { text: "8.8.8.8", isCorrect: false },
        { text: "203.0.113.12", isCorrect: false },
      ],
      explanation: "192.168.x.x addresses are private - they only work inside your home network. 8.8.8.8 is Google's public DNS, and 203.0.113.12 is your public IP (how the internet sees you).",
      why: "Knowing private ranges helps you spot which devices are local and which are on the internet.",
      nextStep: "When you see 192.168.x.x, 10.x.x.x, or 172.16-31.x.x, treat it as local and find the public IP on your router.",
      relatedLayer: "network",
    },
    {
      id: "prompt_mac_purpose",
      question: "What is a MAC address (Local ID) used for?",
      answers: [
        { text: "Routing packets across the internet", isCorrect: false },
        { text: "Identifying devices on the local network", isCorrect: true },
        { text: "Encrypting your data", isCorrect: false },
      ],
      explanation: "MAC addresses are unique hardware identifiers burned into each network device. They're used for delivering data on your local network segment - like apartment numbers within a building. Routers strip MAC addresses when forwarding to the internet.",
      why: "MACs identify devices only on your local network, not across the internet.",
      nextStep: "Use your router's device list to match MAC addresses to real devices when troubleshooting.",
      relatedLayer: "link",
    },
    {
      id: "prompt_guest_network",
      question: "Why would you put guests on a separate network?",
      answers: [
        { text: "To give them faster internet speed", isCorrect: false },
        { text: "To prevent them from accessing your personal devices", isCorrect: true },
        { text: "Because there's a limit to devices on one network", isCorrect: false },
      ],
      explanation: "Guest networks create isolation. Visitors can use the internet, but they can't see or access your personal computers, cameras, or smart devices.",
      why: "Segmentation keeps guest devices from reaching your personal devices if they are compromised.",
      nextStep: "Enable a guest SSID and keep it isolated from your main network.",
      relatedLayer: "network",
    },
    {
      id: "prompt_unknown_device",
      question: "You notice an unknown device on your network. What should you do?",
      answers: [
        { text: "Ignore it - it's probably fine", isCorrect: false },
        { text: "Investigate and possibly block it", isCorrect: true },
        { text: "Unplug your router immediately", isCorrect: false },
      ],
      explanation: "Unknown devices could be forgotten gadgets, neighbors leeching Wi-Fi, or even malicious actors. Check your router's admin page to identify and remove suspicious devices.",
      why: "Unknown devices can indicate shared Wi-Fi abuse or a real intrusion.",
      nextStep: "Identify it in your router and block it or change your Wi-Fi password.",
    },
    {
      id: "prompt_iot_isolation",
      question: "Why are IoT devices (cameras, thermostats) often put on a separate network?",
      answers: [
        { text: "They need special internet settings", isCorrect: false },
        { text: "They're often insecure and could be used to attack other devices", isCorrect: true },
        { text: "They use too much bandwidth", isCorrect: false },
      ],
      explanation: "Many IoT devices have weak security, use default passwords, or don't get updates. Isolating them prevents a compromised camera from spying on your laptop.",
      why: "IoT devices are common entry points; isolation limits how far an attacker can move.",
      nextStep: "Put IoT devices on a separate network or VLAN with limited access.",
      relatedLayer: "network",
    },
  ],
  flows: [
    {
      id: "flow_laptop_bank",
      srcDeviceId: "laptop_work",
      dstLabel: "bank.example",
      protocol: "HTTPS",
      transport: "TCP",
      port: 443,
      encrypted: true,
      category: "web",
    },
    {
      id: "flow_phone_message",
      srcDeviceId: "phone_mom",
      dstLabel: "imessage.apple.com",
      protocol: "iMessage",
      transport: "TCP",
      port: 443,
      encrypted: true,
      category: "chat",
    },
    {
      id: "flow_tv_stream",
      srcDeviceId: "smarttv",
      dstLabel: "netflix.com",
      protocol: "HTTPS",
      transport: "TCP",
      port: 443,
      encrypted: true,
      category: "video",
    },
    {
      id: "flow_camera_stream",
      srcDeviceId: "camera_indoor",
      dstLabel: "cam-cloud.example",
      protocol: "RTSP",
      transport: "UDP",
      port: 554,
      encrypted: false,
      category: "video",
    },
    {
      id: "flow_speaker_voice",
      srcDeviceId: "speaker",
      dstLabel: "alexa.amazon.com",
      protocol: "HTTPS",
      transport: "TCP",
      port: 443,
      encrypted: true,
      category: "chat",
    },
    {
      id: "flow_thermostat_update",
      srcDeviceId: "thermostat",
      dstLabel: "nest.com",
      protocol: "HTTPS",
      transport: "TCP",
      port: 443,
      encrypted: true,
      category: "web",
    },
  ],
  scenarioTasks: [
    {
      id: "family_block_unknown",
      title: "Block the unknown device",
      instruction: "Select the \"Generic Smart Controller\" and block it from your network.",
      actionType: "block_unknown",
      target: { type: "device", id: "mystery_device" },
      successCopy: "You blocked the unknown device, reducing immediate risk.",
      failureCopy: "That isn't the unknown device. Identify the unfamiliar one first.",
      tipCopy: "Unknown devices should be investigated and blocked if they don't belong.",
    },
    {
      id: "family_change_camera_password",
      title: "Change the camera password",
      instruction: "Find the Indoor Camera and change its default password.",
      actionType: "change_password",
      target: { type: "device", id: "camera_indoor" },
      successCopy: "Default password changed - a common IoT weakness is now removed.",
      failureCopy: "Select the Indoor Camera that still has a default password.",
      tipCopy: "Default credentials are one of the most common IoT compromises.",
    },
    {
      id: "family_enable_guest",
      title: "Enable the guest network",
      instruction: "Confirm the guest network is enabled for visitors.",
      actionType: "enable_guest",
      target: { type: "network", id: "guest" },
      successCopy: "Guest access is separated, protecting your personal devices.",
      failureCopy: "Select a device on the guest network to confirm it's enabled.",
      tipCopy: "Guest networks keep visitors from reaching your main devices.",
    },
  ],
};

export const smallBusinessScenario: Scenario = {
  id: "small_business_v1",
  title: "Small Business Office",
  description: "A small business with employees, a server, and customer-facing Wi-Fi. Notice the separation between staff and customer networks.",
  environment: {
    type: "business",
    isp: "BusinessFiber",
    publicIp: "198.51.100.45",
  },
  networks: [
    { id: "corp", ssid: "TechCorp_Staff", security: "WPA3", subnet: "10.0.1.0/24", zone: "main" },
    { id: "guest", ssid: "TechCorp_Guest", security: "WPA2", subnet: "10.0.2.0/24", zone: "guest" },
    { id: "iot", ssid: "TechCorp_Devices", security: "WPA2", subnet: "10.0.3.0/24", zone: "iot" },
  ],
  devices: [
    {
      id: "router",
      type: "router",
      label: "Office Router",
      networkId: "corp",
      ip: "10.0.1.1",
      localId: "00:11:22:33:44:55",
      riskFlags: [],
      description: "Business-grade router with firewall capabilities. Manages all three networks.",
      manufacturer: "Cisco",
      openPorts: [443],
    },
    {
      id: "server",
      type: "server",
      label: "File Server",
      networkId: "corp",
      ip: "10.0.1.10",
      localId: "66:77:88:99:AA:BB",
      riskFlags: [],
      description: "Central file storage for company documents. Access restricted to staff network.",
      manufacturer: "Dell",
      openPorts: [22, 443, 445],
      protocols: ["SMB", "HTTPS", "SSH"],
    },
    {
      id: "laptop_ceo",
      type: "laptop",
      label: "CEO's Laptop",
      networkId: "corp",
      ip: "10.0.1.15",
      localId: "CC:DD:EE:FF:00:11",
      riskFlags: [],
      description: "Executive laptop with access to sensitive company data.",
      manufacturer: "Apple",
      protocols: ["HTTPS", "Email"],
    },
    {
      id: "laptop_employee1",
      type: "laptop",
      label: "Sales Laptop",
      networkId: "corp",
      ip: "10.0.1.20",
      localId: "22:33:44:55:66:77",
      riskFlags: [],
      description: "Employee workstation for sales team member.",
      manufacturer: "Lenovo",
      protocols: ["HTTPS", "CRM"],
    },
    {
      id: "phone_employee",
      type: "phone",
      label: "Work Phone",
      networkId: "corp",
      ip: "10.0.1.25",
      localId: "88:99:AA:BB:CC:DD",
      riskFlags: [],
      description: "Company-issued smartphone for mobile work.",
      manufacturer: "Apple",
    },
    {
      id: "printer",
      type: "printer",
      label: "Office Printer",
      networkId: "iot",
      ip: "10.0.3.10",
      localId: "EE:FF:00:11:22:33",
      riskFlags: ["iot_device", "default_password"],
      description: "Network printer. Warning: Admin password never changed from default!",
      manufacturer: "HP",
      openPorts: [80, 443, 9100],
    },
    {
      id: "customer_phone",
      type: "phone",
      label: "Customer Device",
      networkId: "guest",
      ip: "10.0.2.15",
      localId: "44:55:66:77:88:99",
      riskFlags: [],
      description: "A customer's phone using the guest Wi-Fi while waiting.",
      manufacturer: "Google",
    },
    {
      id: "camera_entrance",
      type: "camera",
      label: "Entrance Camera",
      networkId: "iot",
      ip: "10.0.3.20",
      localId: "AA:BB:CC:DD:EE:FF",
      riskFlags: ["iot_device"],
      description: "Security camera monitoring the main entrance.",
      manufacturer: "Ubiquiti",
      openPorts: [443, 554],
    },
    {
      id: "unknown_laptop",
      type: "unknown",
      label: "Unregistered Device",
      networkId: "corp",
      ip: "10.0.1.99",
      localId: "FF:EE:DD:CC:BB:AA",
      riskFlags: ["unknown_device"],
      description: "This device appeared on the corporate network but isn't registered with IT. Investigate immediately!",
    },
  ],
  events: [
    {
      id: "unknown_device_alert",
      trigger: "onEnter",
      deviceId: "unknown_laptop",
      message: "IT Alert: An unregistered device has connected to the corporate network!",
    },
  ],
  learningPrompts: [
    {
      id: "prompt_10_network",
      question: "What type of IP address range is 10.0.x.x?",
      answers: [
        { text: "Public IP range", isCorrect: false },
        { text: "Private IP range for internal networks", isCorrect: true },
        { text: "Reserved for government use", isCorrect: false },
      ],
      explanation: "10.0.0.0/8 is one of three private IP ranges (along with 172.16.x.x and 192.168.x.x). These addresses work only inside your network and can't be reached directly from the internet.",
      why: "Recognizing private ranges prevents you from assuming a device is publicly reachable.",
      nextStep: "Treat 10.x addresses as internal and look for the public IP on the router.",
      relatedLayer: "network",
    },
    {
      id: "prompt_wpa3",
      question: "Why does the staff network use WPA3 while guest uses WPA2?",
      answers: [
        { text: "WPA3 is slower, only staff can handle it", isCorrect: false },
        { text: "WPA3 provides stronger encryption for sensitive data", isCorrect: true },
        { text: "There's no meaningful difference", isCorrect: false },
      ],
      explanation: "WPA3 offers better protection against password guessing attacks and uses newer encryption. Corporate data deserves the strongest protection available.",
      why: "Stronger Wi-Fi encryption reduces the risk of password guessing and data exposure.",
      nextStep: "Use WPA3 when available and keep WPA2 only for legacy devices.",
    },
    {
      id: "prompt_printer_risk",
      question: "Why is the printer flagged as a security risk?",
      answers: [
        { text: "Printers can't be secure", isCorrect: false },
        { text: "It still has the default password, making it easy to hack", isCorrect: true },
        { text: "It's connected to the wrong network", isCorrect: false },
      ],
      explanation: "Printers with default passwords are often targeted by attackers. They can be used to intercept documents, spread to other devices, or even become part of botnets.",
      why: "Default credentials are a common entry point for attackers.",
      nextStep: "Change default passwords and move printers to a restricted network.",
    },
    {
      id: "prompt_corp_isolation",
      question: "Why can't customers on guest Wi-Fi access the file server?",
      answers: [
        { text: "The file server is turned off", isCorrect: false },
        { text: "Guest network is isolated from corporate network", isCorrect: true },
        { text: "Customers don't have the password", isCorrect: false },
      ],
      explanation: "Network segmentation means different networks can't communicate. Guests get internet access but are completely walled off from internal resources.",
      why: "Segmentation protects internal data even if guest Wi-Fi is compromised.",
      nextStep: "Verify guest Wi-Fi cannot reach internal servers or printers.",
      relatedLayer: "network",
    },
  ],
  flows: [
    {
      id: "flow_server_backup",
      srcDeviceId: "server",
      dstLabel: "backup.internal",
      protocol: "SMB",
      transport: "TCP",
      port: 445,
      encrypted: false,
      category: "file",
    },
    {
      id: "flow_ceo_mail",
      srcDeviceId: "laptop_ceo",
      dstLabel: "mail.example.com",
      protocol: "SMTP",
      transport: "TCP",
      port: 587,
      encrypted: true,
      category: "email",
    },
    {
      id: "flow_sales_crm",
      srcDeviceId: "laptop_employee1",
      dstLabel: "crm.example.com",
      protocol: "HTTPS",
      transport: "TCP",
      port: 443,
      encrypted: true,
      category: "web",
    },
    {
      id: "flow_printer_http",
      srcDeviceId: "printer",
      dstLabel: "printer.local",
      protocol: "HTTP",
      transport: "TCP",
      port: 80,
      encrypted: false,
      category: "web",
    },
    {
      id: "flow_unknown_exfil",
      srcDeviceId: "unknown_laptop",
      dstLabel: "exfil.example",
      protocol: "HTTP",
      transport: "TCP",
      port: 80,
      encrypted: false,
      category: "web",
    },
  ],
  scenarioTasks: [
    {
      id: "business_enable_guest",
      title: "Separate customer Wi-Fi",
      instruction: "Confirm the guest network is enabled for customers.",
      actionType: "enable_guest",
      target: { type: "network", id: "guest" },
      successCopy: "Customers are isolated from internal systems.",
      failureCopy: "Select a device on the guest network to confirm it's enabled.",
      tipCopy: "Guest networks protect internal resources from visitors.",
    },
    {
      id: "business_isolate_printer",
      title: "Isolate the printer",
      instruction: "Move the office printer to the device network or keep it isolated.",
      actionType: "isolate_device",
      target: { type: "device", id: "printer" },
      successCopy: "The printer is isolated from staff devices, reducing risk.",
      failureCopy: "Select the office printer to isolate it.",
      tipCopy: "Printers often have weak security and should be segmented.",
    },
    {
      id: "business_block_unknown",
      title: "Block the unregistered device",
      instruction: "Identify the unregistered device and remove it from the network.",
      actionType: "block_unknown",
      target: { type: "device", id: "unknown_laptop" },
      successCopy: "The unknown device is blocked and no longer a threat.",
      failureCopy: "Select the unregistered device before blocking it.",
      tipCopy: "Unknown corporate devices should be removed immediately.",
    },
  ],
};

export const hotelPublicScenario: Scenario = {
  id: "hotel_public_v1",
  title: "Hotel / Public Wi-Fi",
  description: "A hotel lobby with public Wi-Fi. Notice: All guests share the same network, and you can't trust who else is connected.",
  environment: {
    type: "public",
    isp: "HotelISP",
    publicIp: "192.0.2.100",
  },
  networks: [
    { id: "public", ssid: "GrandHotel_Lobby", security: "Open", subnet: "172.16.0.0/16", zone: "guest" },
    { id: "staff", ssid: "GrandHotel_Staff", security: "WPA3", subnet: "172.17.0.0/16", zone: "main" },
  ],
  devices: [
    {
      id: "router",
      type: "router",
      label: "Hotel Access Point",
      networkId: "public",
      ip: "172.16.0.1",
      localId: "00:AA:BB:CC:DD:EE",
      riskFlags: [],
      description: "Public access point. Warning: Traffic on open networks can be intercepted!",
      manufacturer: "Aruba",
    },
    {
      id: "your_laptop",
      type: "laptop",
      label: "Your Laptop",
      networkId: "public",
      ip: "172.16.45.102",
      localId: "11:22:33:44:55:66",
      riskFlags: [],
      description: "Your personal laptop connected to hotel Wi-Fi. Be careful what you access!",
      manufacturer: "Apple",
      protocols: ["HTTPS", "Email"],
    },
    {
      id: "stranger_laptop",
      type: "laptop",
      label: "Unknown Guest",
      networkId: "public",
      ip: "172.16.45.55",
      localId: "77:88:99:AA:BB:CC",
      riskFlags: [],
      description: "Another guest's laptop. On open Wi-Fi, they could potentially see your traffic...",
    },
    {
      id: "stranger_phone",
      type: "phone",
      label: "Guest Phone",
      networkId: "public",
      ip: "172.16.12.33",
      localId: "DD:EE:FF:00:11:22",
      riskFlags: [],
      description: "A guest's smartphone. Just another device sharing the network with you.",
    },
    {
      id: "suspicious_laptop",
      type: "laptop",
      label: "Suspicious Device",
      networkId: "public",
      ip: "172.16.0.50",
      localId: "33:44:55:66:77:88",
      riskFlags: ["unencrypted_traffic"],
      description: "This laptop has been connected for 12+ hours and seems to be capturing network traffic...",
    },
    {
      id: "business_phone",
      type: "phone",
      label: "Business Traveler",
      networkId: "public",
      ip: "172.16.88.20",
      localId: "99:AA:BB:CC:DD:EE",
      riskFlags: [],
      description: "A business traveler checking emails. Hopefully they're using a VPN!",
      manufacturer: "Apple",
    },
    {
      id: "staff_laptop",
      type: "laptop",
      label: "Front Desk Computer",
      networkId: "staff",
      ip: "172.17.0.10",
      localId: "FF:00:11:22:33:44",
      riskFlags: [],
      description: "Hotel staff computer on a separate, secure network. Guests can't access this.",
      manufacturer: "Dell",
    },
    {
      id: "fake_ap",
      type: "unknown",
      label: "GrandHotel_Free_WiFi",
      networkId: "public",
      ip: "172.16.0.99",
      localId: "00:00:00:00:00:01",
      riskFlags: ["unknown_device"],
      description: "Wait... is this a legitimate hotel access point, or an 'evil twin' set up by an attacker?",
    },
  ],
  events: [
    {
      id: "evil_twin_warning",
      trigger: "onDeviceClick",
      deviceId: "fake_ap",
      message: "Warning: This might be an 'evil twin' attack! Attackers create fake networks with similar names to intercept your data.",
    },
  ],
  learningPrompts: [
    {
      id: "prompt_open_wifi",
      question: "What does 'Open' network security mean?",
      answers: [
        { text: "Anyone can join without a password", isCorrect: true },
        { text: "The network has no firewall", isCorrect: false },
        { text: "The Wi-Fi signal is publicly visible", isCorrect: false },
      ],
      explanation: "Open networks have no encryption. This means anyone nearby can potentially see your traffic - it's like sending postcards instead of sealed letters.",
      why: "Open Wi-Fi lets nearby users observe traffic, which increases risk for sensitive data.",
      nextStep: "Avoid sensitive logins on open Wi-Fi or use a VPN.",
    },
    {
      id: "prompt_evil_twin",
      question: "What is an 'evil twin' attack?",
      answers: [
        { text: "When someone clones your device", isCorrect: false },
        { text: "A fake Wi-Fi network that mimics a legitimate one", isCorrect: true },
        { text: "When two routers interfere with each other", isCorrect: false },
      ],
      explanation: "Attackers set up fake access points with names like 'Hotel_Free_WiFi' to lure victims. When you connect, they can see everything you do.",
      why: "Fake SSIDs can capture your traffic and steal credentials.",
      nextStep: "Verify the official SSID with staff and turn off auto-join for public Wi-Fi.",
    },
    {
      id: "prompt_public_private_ip",
      question: "On public Wi-Fi, why might your IP still be private (e.g., 172.16.x.x)?",
      answers: [
        { text: "Because the hotspot uses NAT and private addressing", isCorrect: true },
        { text: "Because public Wi-Fi always gives out public IPs", isCorrect: false },
        { text: "Because private IPs are only for home networks", isCorrect: false },
      ],
      explanation: "Public Wi-Fi often uses private IP ranges and NAT. Your device has a private address locally, while the hotspot uses one public IP to reach the internet.",
      why: "Private IPs can exist in public places too; NAT hides many devices behind one public IP.",
      nextStep: "Look for the NAT boundary: your device has a private IP and the hotspot has the public IP.",
      relatedLayer: "network",
    },
    {
      id: "prompt_https_importance",
      question: "On public Wi-Fi, why is HTTPS especially important?",
      answers: [
        { text: "HTTPS makes websites load faster", isCorrect: false },
        { text: "HTTPS encrypts your data so others on the network can't read it", isCorrect: true },
        { text: "HTTPS prevents viruses", isCorrect: false },
      ],
      explanation: "HTTPS uses TLS encryption to create a secure tunnel between you and the website. Even if someone captures your traffic, they see encrypted data instead of your passwords and personal information.",
      why: "HTTPS keeps your data readable only to you and the website, even on untrusted networks.",
      nextStep: "Check for HTTPS (lock icon) before entering passwords or personal data.",
      relatedLayer: "application",
    },
    {
      id: "prompt_vpn",
      question: "What does a VPN do on public Wi-Fi?",
      answers: [
        { text: "Makes your internet faster", isCorrect: false },
        { text: "Creates an encrypted tunnel for all your traffic", isCorrect: true },
        { text: "Blocks other users from connecting", isCorrect: false },
      ],
      explanation: "A VPN encrypts everything leaving your device, not just web traffic. It's like putting all your postcards in a locked box before sending them.",
      why: "A VPN protects all apps, not just browsers, on untrusted networks.",
      nextStep: "Use a reputable VPN when working or banking on public Wi-Fi.",
      relatedLayer: "network",
    },
    {
      id: "prompt_safe_behavior",
      question: "What should you avoid doing on public Wi-Fi?",
      answers: [
        { text: "Browsing news websites", isCorrect: false },
        { text: "Logging into your bank without a VPN", isCorrect: true },
        { text: "Checking the weather", isCorrect: false },
      ],
      explanation: "Sensitive activities like banking should wait for a secure network or require a VPN. Even HTTPS can't protect against all attacks on compromised networks.",
      why: "Some actions are higher-risk on public networks, even with encryption.",
      nextStep: "Delay banking or change passwords until you're on a trusted network.",
    },
  ],
  flows: [
    {
      id: "flow_laptop_bank",
      srcDeviceId: "your_laptop",
      dstLabel: "bank.example",
      protocol: "HTTPS",
      transport: "TCP",
      port: 443,
      encrypted: true,
      category: "web",
    },
    {
      id: "flow_stranger_news",
      srcDeviceId: "stranger_laptop",
      dstLabel: "news.example",
      protocol: "HTTP",
      transport: "TCP",
      port: 80,
      encrypted: false,
      category: "web",
    },
    {
      id: "flow_business_vpn",
      srcDeviceId: "business_phone",
      dstLabel: "vpn.example",
      protocol: "WireGuard",
      transport: "UDP",
      port: 51820,
      encrypted: true,
      category: "remote",
    },
    {
      id: "flow_suspicious_capture",
      srcDeviceId: "suspicious_laptop",
      dstLabel: "traffic.capture",
      protocol: "HTTP",
      transport: "TCP",
      port: 80,
      encrypted: false,
      category: "web",
    },
  ],
  scenarioTasks: [
    {
      id: "hotel_verify_ssid",
      title: "Verify the official Wi-Fi",
      instruction: "Select the real hotel access point, not the fake one.",
      actionType: "verify_ssid",
      target: { type: "device", id: "router" },
      successCopy: "You identified the official access point.",
      failureCopy: "That isn't the official hotel access point. Try again.",
      tipCopy: "Attackers often create look-alike Wi-Fi names to trick guests.",
    },
    {
      id: "hotel_block_fake_ap",
      title: "Report the fake access point",
      instruction: "Identify the suspicious Wi‑Fi device and flag it.",
      actionType: "block_unknown",
      target: { type: "device", id: "fake_ap" },
      successCopy: "The fake access point is flagged and avoided.",
      failureCopy: "Select the suspicious access point before reporting it.",
      tipCopy: "If a network name looks off, avoid it and alert staff.",
    },
  ],
};

export const allScenarios: Scenario[] = [familyIoTScenario, smallBusinessScenario, hotelPublicScenario];
