import type { Scenario } from "./schema";

export const familyIoTScenario: Scenario = {
  id: "family_iot_sprawl_v1",
  title: "Family Home with IoT Sprawl",
  description: "A typical suburban home with multiple family members and various smart devices. Notice how IoT devices are isolated on their own network for security.",
  environment: {
    type: "home",
    isp: "FictionalNet",
    publicIp: "203.0.113.12",
  },
  networks: [
    { id: "main", ssid: "MapleHouse_Main", security: "WPA2", subnet: "192.168.10.0/24", zone: "main" },
    { id: "guest", ssid: "MapleHouse_Guest", security: "WPA2", subnet: "192.168.20.0/24", zone: "guest" },
    { id: "iot", ssid: "MapleHouse_IoT", security: "WPA2", subnet: "192.168.30.0/24", zone: "iot" },
  ],
  devices: [
    {
      id: "router",
      type: "router",
      label: "Home Router",
      networkId: "main",
      ip: "192.168.10.1",
      localId: "A0:B1:C2:D3:E4:F5",
      riskFlags: [],
      description: "The central hub of your home network. All traffic flows through this device.",
      manufacturer: "NetGear",
      openPorts: [80, 443],
    },
    {
      id: "laptop_work",
      type: "laptop",
      label: "Work Laptop",
      networkId: "main",
      ip: "192.168.10.14",
      localId: "AA:BB:CC:11:22:33",
      riskFlags: [],
      description: "A work-issued laptop used for remote work. Connected to the main network for full access.",
      manufacturer: "Dell",
      protocols: ["HTTPS", "SSH", "RDP"],
    },
    {
      id: "phone_mom",
      type: "phone",
      label: "Mom's iPhone",
      networkId: "main",
      ip: "192.168.10.22",
      localId: "DD:EE:FF:44:55:66",
      riskFlags: [],
      description: "Personal smartphone with banking and social media apps.",
      manufacturer: "Apple",
      protocols: ["HTTPS", "iMessage"],
    },
    {
      id: "tablet_kid",
      type: "tablet",
      label: "Kids' iPad",
      networkId: "main",
      ip: "192.168.10.31",
      localId: "11:22:33:AA:BB:CC",
      riskFlags: [],
      description: "Tablet used by children for education and entertainment.",
      manufacturer: "Apple",
      protocols: ["HTTPS", "YouTube"],
    },
    {
      id: "smarttv",
      type: "smarttv",
      label: "Living Room TV",
      networkId: "iot",
      ip: "192.168.30.10",
      localId: "77:88:99:AA:BB:CC",
      riskFlags: ["iot_device"],
      description: "Smart TV with streaming apps. Isolated on IoT network to limit potential vulnerabilities.",
      manufacturer: "Samsung",
      protocols: ["HTTPS", "Netflix", "Disney+"],
    },
    {
      id: "camera_indoor",
      type: "camera",
      label: "Indoor Camera",
      networkId: "iot",
      ip: "192.168.30.21",
      localId: "EE:FF:00:11:22:33",
      riskFlags: ["iot_device", "default_password"],
      description: "Security camera monitoring the living room. Warning: Still using default password!",
      manufacturer: "Wyze",
      openPorts: [80, 554],
    },
    {
      id: "thermostat",
      type: "thermostat",
      label: "Smart Thermostat",
      networkId: "iot",
      ip: "192.168.30.15",
      localId: "44:55:66:77:88:99",
      riskFlags: ["iot_device"],
      description: "Controls home temperature and can be accessed remotely.",
      manufacturer: "Nest",
      protocols: ["HTTPS"],
    },
    {
      id: "speaker",
      type: "speaker",
      label: "Voice Assistant",
      networkId: "iot",
      ip: "192.168.30.25",
      localId: "BB:CC:DD:EE:FF:00",
      riskFlags: ["iot_device"],
      description: "Smart speaker with voice assistant. Always listening for wake word.",
      manufacturer: "Amazon",
      protocols: ["HTTPS", "Alexa"],
    },
    {
      id: "guest_phone",
      type: "phone",
      label: "Guest's Phone",
      networkId: "guest",
      ip: "192.168.20.5",
      localId: "12:34:56:78:9A:BC",
      riskFlags: [],
      description: "A visitor's phone connected to the guest network. Cannot access main network devices.",
      manufacturer: "Samsung",
    },
    {
      id: "mystery_device",
      type: "unknown",
      label: "Generic Smart Controller",
      networkId: "iot",
      ip: "192.168.30.99",
      localId: "FF:00:11:22:33:44",
      riskFlags: ["unknown_device", "forgotten_device"],
      description: "An unidentified device on your network. When did this connect? What is it?",
    },
    {
      id: "old_tablet",
      type: "tablet",
      label: "Old Tablet (Inactive)",
      networkId: "main",
      ip: "192.168.10.50",
      localId: "99:AA:BB:CC:DD:EE",
      riskFlags: ["forgotten_device", "outdated_firmware"],
      description: "An old tablet that hasn't been updated in 2 years. Still connected but rarely used.",
      manufacturer: "Samsung",
    },
  ],
  events: [
    {
      id: "unknown_device_reveal",
      trigger: "onEnter",
      deviceId: "mystery_device",
      message: "An unfamiliar device appears on your IoT network. You don't remember adding this...",
    },
  ],
  learningPrompts: [
    {
      id: "prompt_private_ip",
      question: "Which of these is a private IP address?",
      answers: [
        { text: "192.168.10.14", isCorrect: true },
        { text: "8.8.8.8", isCorrect: false },
        { text: "203.0.113.12", isCorrect: false },
      ],
      explanation: "192.168.x.x addresses are private - they only work inside your home network. 8.8.8.8 is Google's public DNS, and 203.0.113.12 is your public IP (how the internet sees you).",
      relatedLayer: "network",
    },
    {
      id: "prompt_mac_purpose",
      question: "What is a MAC address (Local ID) used for?",
      answers: [
        { text: "Routing packets across the internet", isCorrect: false },
        { text: "Identifying devices on the local network", isCorrect: true },
        { text: "Encrypting your data", isCorrect: false },
      ],
      explanation: "MAC addresses are unique hardware identifiers burned into each network device. They're used for delivering data on your local network segment - like apartment numbers within a building. Routers strip MAC addresses when forwarding to the internet.",
      relatedLayer: "link",
    },
    {
      id: "prompt_guest_network",
      question: "Why would you put guests on a separate network?",
      answers: [
        { text: "To give them faster internet speed", isCorrect: false },
        { text: "To prevent them from accessing your personal devices", isCorrect: true },
        { text: "Because there's a limit to devices on one network", isCorrect: false },
      ],
      explanation: "Guest networks create isolation. Visitors can use the internet, but they can't see or access your personal computers, cameras, or smart devices.",
      relatedLayer: "network",
    },
    {
      id: "prompt_unknown_device",
      question: "You notice an unknown device on your network. What should you do?",
      answers: [
        { text: "Ignore it - it's probably fine", isCorrect: false },
        { text: "Investigate and possibly block it", isCorrect: true },
        { text: "Unplug your router immediately", isCorrect: false },
      ],
      explanation: "Unknown devices could be forgotten gadgets, neighbors leeching Wi-Fi, or even malicious actors. Check your router's admin page to identify and remove suspicious devices.",
    },
    {
      id: "prompt_iot_isolation",
      question: "Why are IoT devices (cameras, thermostats) often put on a separate network?",
      answers: [
        { text: "They need special internet settings", isCorrect: false },
        { text: "They're often insecure and could be used to attack other devices", isCorrect: true },
        { text: "They use too much bandwidth", isCorrect: false },
      ],
      explanation: "Many IoT devices have weak security, use default passwords, or don't get updates. Isolating them prevents a compromised camera from spying on your laptop.",
      relatedLayer: "network",
    },
  ],
};

export const smallBusinessScenario: Scenario = {
  id: "small_business_v1",
  title: "Small Business Office",
  description: "A small business with employees, a server, and customer-facing Wi-Fi. Notice the separation between staff and customer networks.",
  environment: {
    type: "business",
    isp: "BusinessFiber",
    publicIp: "198.51.100.45",
  },
  networks: [
    { id: "corp", ssid: "TechCorp_Staff", security: "WPA3", subnet: "10.0.1.0/24", zone: "main" },
    { id: "guest", ssid: "TechCorp_Guest", security: "WPA2", subnet: "10.0.2.0/24", zone: "guest" },
    { id: "iot", ssid: "TechCorp_Devices", security: "WPA2", subnet: "10.0.3.0/24", zone: "iot" },
  ],
  devices: [
    {
      id: "router",
      type: "router",
      label: "Office Router",
      networkId: "corp",
      ip: "10.0.1.1",
      localId: "00:11:22:33:44:55",
      riskFlags: [],
      description: "Business-grade router with firewall capabilities. Manages all three networks.",
      manufacturer: "Cisco",
      openPorts: [443],
    },
    {
      id: "server",
      type: "laptop",
      label: "File Server",
      networkId: "corp",
      ip: "10.0.1.10",
      localId: "66:77:88:99:AA:BB",
      riskFlags: [],
      description: "Central file storage for company documents. Access restricted to staff network.",
      manufacturer: "Dell",
      openPorts: [22, 443, 445],
      protocols: ["SMB", "HTTPS", "SSH"],
    },
    {
      id: "laptop_ceo",
      type: "laptop",
      label: "CEO's Laptop",
      networkId: "corp",
      ip: "10.0.1.15",
      localId: "CC:DD:EE:FF:00:11",
      riskFlags: [],
      description: "Executive laptop with access to sensitive company data.",
      manufacturer: "Apple",
      protocols: ["HTTPS", "Email"],
    },
    {
      id: "laptop_employee1",
      type: "laptop",
      label: "Sales Laptop",
      networkId: "corp",
      ip: "10.0.1.20",
      localId: "22:33:44:55:66:77",
      riskFlags: [],
      description: "Employee workstation for sales team member.",
      manufacturer: "Lenovo",
      protocols: ["HTTPS", "CRM"],
    },
    {
      id: "phone_employee",
      type: "phone",
      label: "Work Phone",
      networkId: "corp",
      ip: "10.0.1.25",
      localId: "88:99:AA:BB:CC:DD",
      riskFlags: [],
      description: "Company-issued smartphone for mobile work.",
      manufacturer: "Apple",
    },
    {
      id: "printer",
      type: "printer",
      label: "Office Printer",
      networkId: "iot",
      ip: "10.0.3.10",
      localId: "EE:FF:00:11:22:33",
      riskFlags: ["iot_device", "default_password"],
      description: "Network printer. Warning: Admin password never changed from default!",
      manufacturer: "HP",
      openPorts: [80, 443, 9100],
    },
    {
      id: "customer_phone",
      type: "phone",
      label: "Customer Device",
      networkId: "guest",
      ip: "10.0.2.15",
      localId: "44:55:66:77:88:99",
      riskFlags: [],
      description: "A customer's phone using the guest Wi-Fi while waiting.",
      manufacturer: "Google",
    },
    {
      id: "camera_entrance",
      type: "camera",
      label: "Entrance Camera",
      networkId: "iot",
      ip: "10.0.3.20",
      localId: "AA:BB:CC:DD:EE:FF",
      riskFlags: ["iot_device"],
      description: "Security camera monitoring the main entrance.",
      manufacturer: "Ubiquiti",
      openPorts: [443, 554],
    },
    {
      id: "unknown_laptop",
      type: "unknown",
      label: "Unregistered Device",
      networkId: "corp",
      ip: "10.0.1.99",
      localId: "FF:EE:DD:CC:BB:AA",
      riskFlags: ["unknown_device"],
      description: "This device appeared on the corporate network but isn't registered with IT. Investigate immediately!",
    },
  ],
  events: [
    {
      id: "unknown_device_alert",
      trigger: "onEnter",
      deviceId: "unknown_laptop",
      message: "IT Alert: An unregistered device has connected to the corporate network!",
    },
  ],
  learningPrompts: [
    {
      id: "prompt_10_network",
      question: "What type of IP address range is 10.0.x.x?",
      answers: [
        { text: "Public IP range", isCorrect: false },
        { text: "Private IP range for internal networks", isCorrect: true },
        { text: "Reserved for government use", isCorrect: false },
      ],
      explanation: "10.0.0.0/8 is one of three private IP ranges (along with 172.16.x.x and 192.168.x.x). These addresses work only inside your network and can't be reached directly from the internet.",
      relatedLayer: "network",
    },
    {
      id: "prompt_wpa3",
      question: "Why does the staff network use WPA3 while guest uses WPA2?",
      answers: [
        { text: "WPA3 is slower, only staff can handle it", isCorrect: false },
        { text: "WPA3 provides stronger encryption for sensitive data", isCorrect: true },
        { text: "There's no meaningful difference", isCorrect: false },
      ],
      explanation: "WPA3 offers better protection against password guessing attacks and uses newer encryption. Corporate data deserves the strongest protection available.",
    },
    {
      id: "prompt_printer_risk",
      question: "Why is the printer flagged as a security risk?",
      answers: [
        { text: "Printers can't be secure", isCorrect: false },
        { text: "It still has the default password, making it easy to hack", isCorrect: true },
        { text: "It's connected to the wrong network", isCorrect: false },
      ],
      explanation: "Printers with default passwords are often targeted by attackers. They can be used to intercept documents, spread to other devices, or even become part of botnets.",
    },
    {
      id: "prompt_corp_isolation",
      question: "Why can't customers on guest Wi-Fi access the file server?",
      answers: [
        { text: "The file server is turned off", isCorrect: false },
        { text: "Guest network is isolated from corporate network", isCorrect: true },
        { text: "Customers don't have the password", isCorrect: false },
      ],
      explanation: "Network segmentation means different networks can't communicate. Guests get internet access but are completely walled off from internal resources.",
      relatedLayer: "network",
    },
  ],
};

export const hotelPublicScenario: Scenario = {
  id: "hotel_public_v1",
  title: "Hotel / Public Wi-Fi",
  description: "A hotel lobby with public Wi-Fi. Notice: All guests share the same network, and you can't trust who else is connected.",
  environment: {
    type: "public",
    isp: "HotelISP",
    publicIp: "192.0.2.100",
  },
  networks: [
    { id: "public", ssid: "GrandHotel_Lobby", security: "Open", subnet: "172.16.0.0/16", zone: "guest" },
    { id: "staff", ssid: "GrandHotel_Staff", security: "WPA3", subnet: "172.17.0.0/16", zone: "main" },
  ],
  devices: [
    {
      id: "router",
      type: "router",
      label: "Hotel Access Point",
      networkId: "public",
      ip: "172.16.0.1",
      localId: "00:AA:BB:CC:DD:EE",
      riskFlags: [],
      description: "Public access point. Warning: Traffic on open networks can be intercepted!",
      manufacturer: "Aruba",
    },
    {
      id: "your_laptop",
      type: "laptop",
      label: "Your Laptop",
      networkId: "public",
      ip: "172.16.45.102",
      localId: "11:22:33:44:55:66",
      riskFlags: [],
      description: "Your personal laptop connected to hotel Wi-Fi. Be careful what you access!",
      manufacturer: "Apple",
      protocols: ["HTTPS", "Email"],
    },
    {
      id: "stranger_laptop",
      type: "laptop",
      label: "Unknown Guest",
      networkId: "public",
      ip: "172.16.45.55",
      localId: "77:88:99:AA:BB:CC",
      riskFlags: [],
      description: "Another guest's laptop. On open Wi-Fi, they could potentially see your traffic...",
    },
    {
      id: "stranger_phone",
      type: "phone",
      label: "Guest Phone",
      networkId: "public",
      ip: "172.16.12.33",
      localId: "DD:EE:FF:00:11:22",
      riskFlags: [],
      description: "A guest's smartphone. Just another device sharing the network with you.",
    },
    {
      id: "suspicious_laptop",
      type: "laptop",
      label: "Suspicious Device",
      networkId: "public",
      ip: "172.16.0.50",
      localId: "33:44:55:66:77:88",
      riskFlags: ["unencrypted_traffic"],
      description: "This laptop has been connected for 12+ hours and seems to be capturing network traffic...",
    },
    {
      id: "business_phone",
      type: "phone",
      label: "Business Traveler",
      networkId: "public",
      ip: "172.16.88.20",
      localId: "99:AA:BB:CC:DD:EE",
      riskFlags: [],
      description: "A business traveler checking emails. Hopefully they're using a VPN!",
      manufacturer: "Apple",
    },
    {
      id: "staff_laptop",
      type: "laptop",
      label: "Front Desk Computer",
      networkId: "staff",
      ip: "172.17.0.10",
      localId: "FF:00:11:22:33:44",
      riskFlags: [],
      description: "Hotel staff computer on a separate, secure network. Guests can't access this.",
      manufacturer: "Dell",
    },
    {
      id: "fake_ap",
      type: "unknown",
      label: "GrandHotel_Free_WiFi",
      networkId: "public",
      ip: "172.16.0.99",
      localId: "00:00:00:00:00:01",
      riskFlags: ["unknown_device"],
      description: "Wait... is this a legitimate hotel access point, or an 'evil twin' set up by an attacker?",
    },
  ],
  events: [
    {
      id: "evil_twin_warning",
      trigger: "onDeviceClick",
      deviceId: "fake_ap",
      message: "Warning: This might be an 'evil twin' attack! Attackers create fake networks with similar names to intercept your data.",
    },
  ],
  learningPrompts: [
    {
      id: "prompt_open_wifi",
      question: "What does 'Open' network security mean?",
      answers: [
        { text: "Anyone can join without a password", isCorrect: true },
        { text: "The network has no firewall", isCorrect: false },
        { text: "The Wi-Fi signal is publicly visible", isCorrect: false },
      ],
      explanation: "Open networks have no encryption. This means anyone nearby can potentially see your traffic - it's like sending postcards instead of sealed letters.",
    },
    {
      id: "prompt_evil_twin",
      question: "What is an 'evil twin' attack?",
      answers: [
        { text: "When someone clones your device", isCorrect: false },
        { text: "A fake Wi-Fi network that mimics a legitimate one", isCorrect: true },
        { text: "When two routers interfere with each other", isCorrect: false },
      ],
      explanation: "Attackers set up fake access points with names like 'Hotel_Free_WiFi' to lure victims. When you connect, they can see everything you do.",
    },
    {
      id: "prompt_https_importance",
      question: "On public Wi-Fi, why is HTTPS especially important?",
      answers: [
        { text: "HTTPS makes websites load faster", isCorrect: false },
        { text: "HTTPS encrypts your data so others on the network can't read it", isCorrect: true },
        { text: "HTTPS prevents viruses", isCorrect: false },
      ],
      explanation: "HTTPS uses TLS encryption to create a secure tunnel between you and the website. Even if someone captures your traffic, they see encrypted data instead of your passwords and personal information.",
      relatedLayer: "application",
    },
    {
      id: "prompt_vpn",
      question: "What does a VPN do on public Wi-Fi?",
      answers: [
        { text: "Makes your internet faster", isCorrect: false },
        { text: "Creates an encrypted tunnel for all your traffic", isCorrect: true },
        { text: "Blocks other users from connecting", isCorrect: false },
      ],
      explanation: "A VPN encrypts everything leaving your device, not just web traffic. It's like putting all your postcards in a locked box before sending them.",
      relatedLayer: "network",
    },
    {
      id: "prompt_safe_behavior",
      question: "What should you avoid doing on public Wi-Fi?",
      answers: [
        { text: "Browsing news websites", isCorrect: false },
        { text: "Logging into your bank without a VPN", isCorrect: true },
        { text: "Checking the weather", isCorrect: false },
      ],
      explanation: "Sensitive activities like banking should wait for a secure network or require a VPN. Even HTTPS can't protect against all attacks on compromised networks.",
    },
  ],
};

export const allScenarios: Scenario[] = [familyIoTScenario, smallBusinessScenario, hotelPublicScenario];
